---
- hosts: web
  become: yes
  tasks:

    - name: Installer Docker
      yum:
        name: docker
        state: present

    - name: Démarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ajouter ec2-user au groupe docker
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Installer Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Créer le dossier app
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user

    - name: Créer le dossier nginx
      file:
        path: /home/ec2-user/app/nginx
        state: directory
        owner: ec2-user

    - name: Créer le dossier backend
      file:
        path: /home/ec2-user/app/backend
        state: directory
        owner: ec2-user

    - name: Copier docker-compose.yml
      copy:
        src: ../app/docker-compose.yml
        dest: /home/ec2-user/app/docker-compose.yml

    - name: Copier nginx config
      copy:
        src: ../app/nginx/default.conf
        dest: /home/ec2-user/app/nginx/default.conf

    - name: Copier package.json
      copy:
        src: ../app/backend/package.json
        dest: /home/ec2-user/app/backend/package.json

    - name: Copier index.js
      copy:
        src: ../app/backend/index.js
        dest: /home/ec2-user/app/backend/index.js

    - name: Arrêter les conteneurs
      shell: /usr/local/bin/docker-compose down
      args:
        chdir: /home/ec2-user/app
      ignore_errors: yes

    - name: Lancer les conteneurs
      shell: /usr/local/bin/docker-compose up -d
      args:
        chdir: /home/ec2-user/app
